{% set name = "harfbuzz" %}
{% set version = "1.8.4" %}
{% set sha256 = "3c592f86fa0da69e2e0e98cae9f5d5b61def3bb7948aa00ca45748f27fa545fd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.freedesktop.org/software/{{ name }}/release/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - automake
    - libtool
    - pkg-config
    - pthread-stubs
    - python >=2.7,<3
    - {{ compiler('c') }}
  host:
    - cairo
    - glib
    - freetype
    - icu
    - graphite2
    - gobject-introspection 1.55.*
  run:
    - cairo
    - glib
    - freetype
    - icu
    - graphite2

test:
  commands:
    # Libraries/headers.
    {% set libs = [
        "libharfbuzz-icu",
        "libharfbuzz"
        ] %}
    {% for lib in libs %}
    - test -f $PREFIX/lib/{{ lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/{{ lib }}.so  # [linux]
    {% endfor %}
    - test -f $PREFIX/include/harfbuzz/hb-ft.h  # [not win]
    # CLI tests.
    - hb-view --version  # [linux]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
  license: MIT
  license_file: COPYING
  summary: 'An OpenType text shaping engine.'
  description: |
    HarfBuzz is a text shaping library. New Harbuzz targets various font
    technologies while Old HarfBuzz targets only OpenType fonts.
  doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
  dev_url: https://github.com/behdad/harfbuzz

extra:
  recipe-maintainers:
    - ocefpaf
    - pkgw
